/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project   : ELE3000_v0_4
**     Processor : MC9S12XDP512BMPV
**     Version   : Component 02.003, Driver 01.05, CPU db: 2.87.229
**     Datasheet : MC9S12XDP512RMV2 Rev. 2.18 May 2008
**     Date/Time : 2012-06-05, 20:48
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/
/* MODULE MCUinit */

#include <MC9S12XDP512.h>              /* I/O map for MC9S12XDP512BMPV */
#include "MCUinit.h"

/* Standard ANSI C types */
#ifndef int8_t
typedef signed char int8_t;
#endif
#ifndef int16_t
typedef signed int   int16_t;
#endif
#ifndef int32_t
typedef signed long int    int32_t;
#endif

#ifndef uint8_t
typedef unsigned char       uint8_t;
#endif
#ifndef uint16_t
typedef unsigned int  uint16_t;
#endif
#ifndef uint32_t
typedef unsigned long int   uint32_t;
#endif

#define CGM_DELAY  5119U

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
#include <hidef.h>

extern unsigned int freins, accel, accel1, accel2;
extern void SafetyCheck(void);
extern void SpiSend(unsigned int data);
void emitReadyToDriveSound(void);

/* End of user declarations and definitions */

extern void near _Startup(void);

#pragma CODE_SEG __NEAR_SEG NON_BANKED

static void MCU_init_reset(void);
/*
** ===================================================================
**     Method      :  MCU_init_reset (component MC9S12XDP512_112)
**
**     Description :
**         Device initialization code for after reset initialization.
** ===================================================================
*/
static void MCU_init_reset(void)
{

  /*  Initialization of memory configuration */
  /* MMCCTL1: EROMON=0,ROMHM=0,ROMON=1 */
  MMCCTL1 = 1U;                                      
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  DIRECT = 0U;                                      
  /* IVBR: IVB_ADDR=255 */
  IVBR = 255U;                                      
  /* ECLKCTL: NECLK=0,NCLKX2=1,EDIV1=0,EDIV0=0 */
  ECLKCTL = 64U;                                      
  /* Jump to the default entry point */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm jmp _Startup;
  /*lint -restore Enable MISRA rule (1.1) checking. */
} /*MCU_init*/

#pragma CODE_SEG DEFAULT
#pragma MESSAGE DISABLE C12056



/*
** ===================================================================
**     Method      :  MCU_init (component MC9S12XDP512_112)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{

  /* ### MC9S12XDP512_112 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,PLLWAI=0,RTIWAI=0,COPWAI=0 */
  CLKSEL = 0U;                         /* Select clock source from XTAL and set bits in CLKSEL reg. */
  /* PLLCTL: CME=1,PLLON=0,AUTO=1,ACQ=1,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  PLLCTL = 177U;                       /* Disable the PLL */
  /* SYNR: SYN5=0,SYN4=0,SYN3=0,SYN2=1,SYN1=0,SYN0=0 */
  SYNR = 4U;                           /* Set the multiplier register */
  /* REFDV: REFDV5=0,REFDV4=0,REFDV3=0,REFDV2=0,REFDV1=0,REFDV0=1 */
  REFDV = 1U;                          /* Set the divider register */
  /* PLLCTL: CME=1,PLLON=1,AUTO=1,ACQ=1,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  PLLCTL = 241U;                                      
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  CLKSEL |= (unsigned char)128U;       /* Select clock source from PLL */
  /* Initialization of RAM Protection (MMC module) */
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name          Description */
  INT_CFADDR = 16U;                                      
  INT_CFDATA1 = 1U;                    /*  0x09  0xFF12   1   no   ivReserved119 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x0A  0xFF14   1   no   ivReserved118 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x0B  0xFF16   1   no   ivReserved117 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x0C  0xFF18   1   no   ivReserved116 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x0D  0xFF1A   1   no   ivReserved115 unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x0E  0xFF1C   1   no   ivReserved114 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x0F  0xFF1E   1   no   ivReserved113 unused by PE */
  INT_CFADDR = 32U;                                      
  INT_CFDATA0 = 1U;                    /*  0x10  0xFF20   1   no   ivReserved112 unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x11  0xFF22   1   no   ivReserved111 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x12  0xFF24   1   no   ivReserved110 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x13  0xFF26   1   no   ivReserved109 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x14  0xFF28   1   no   ivReserved108 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x15  0xFF2A   1   no   ivReserved107 unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x16  0xFF2C   1   no   ivReserved106 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x17  0xFF2E   1   no   ivReserved105 unused by PE */
  INT_CFADDR = 48U;                                      
  INT_CFDATA0 = 1U;                    /*  0x18  0xFF30   1   no   ivReserved104 unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x19  0xFF32   1   no   ivReserved103 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x1A  0xFF34   1   no   ivReserved102 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x1B  0xFF36   1   no   ivReserved101 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x1C  0xFF38   1   no   ivReserved100 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x1D  0xFF3A   1   no   ivReserved99  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x1E  0xFF3C   1   no   ivReserved98  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x1F  0xFF3E   1   no   ivReserved97  unused by PE */
  INT_CFADDR = 64U;                                      
  INT_CFDATA0 = 1U;                    /*  0x20  0xFF40   1   no   ivReserved96  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x21  0xFF42   1   no   ivReserved95  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x22  0xFF44   1   no   ivReserved94  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x23  0xFF46   1   no   ivReserved93  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x24  0xFF48   1   no   ivReserved92  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x25  0xFF4A   1   no   ivReserved91  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x26  0xFF4C   1   no   ivReserved90  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x27  0xFF4E   1   no   ivReserved89  unused by PE */
  INT_CFADDR = 80U;                                      
  INT_CFDATA0 = 1U;                    /*  0x28  0xFF50   1   no   ivReserved88  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x29  0xFF52   1   no   ivReserved87  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x2A  0xFF54   1   no   ivReserved86  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x2B  0xFF56   1   no   ivReserved85  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x2C  0xFF58   1   no   ivReserved84  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x2D  0xFF5A   1   no   ivReserved83  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x2E  0xFF5C   1   no   ivReserved82  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x2F  0xFF5E   1   no   ivReserved81  unused by PE */
  INT_CFADDR = 96U;                                      
  INT_CFDATA0 = 1U;                    /*  0x30  0xFF60   1   -    ivVxsramav    unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x31  0xFF62   1   -    ivVxsei       unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x32  0xFF64   1   no   ivVxst7       unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x33  0xFF66   1   no   ivVxst6       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x34  0xFF68   1   no   ivVxst5       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x35  0xFF6A   1   no   ivVxst4       unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x36  0xFF6C   1   no   ivVxst3       unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x37  0xFF6E   1   no   ivVxst2       unused by PE */
  INT_CFADDR = 112U;                                      
  INT_CFDATA0 = 1U;                    /*  0x38  0xFF70   1   no   ivVxst1       unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x39  0xFF72   1   no   ivVxst0       unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x3A  0xFF74   1   no   ivVpit3       unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x3B  0xFF76   1   no   ivVpit2       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x3C  0xFF78   1   no   ivVpit1       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x3D  0xFF7A   1   no   ivVpit0       unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x3E  0xFF7C   1   no   ivVReserved65 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x3F  0xFF7E   1   no   ivVapi        unused by PE */
  INT_CFADDR = 128U;                                      
  INT_CFDATA0 = 1U;                    /*  0x40  0xFF80   1   no   ivVlvi        unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x41  0xFF82   1   no   ivVReserved62 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x42  0xFF84   1   no   ivVsci5       unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x43  0xFF86   1   no   ivVsci4       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x44  0xFF88   1   no   ivVsci3       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x45  0xFF8A   1   no   ivVsci2       unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x46  0xFF8C   1   no   ivVpwmesdn    unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x47  0xFF8E   1   no   ivVportp      unused by PE */
  INT_CFADDR = 144U;                                      
  INT_CFDATA0 = 1U;                    /*  0x48  0xFF90   1   no   ivVcan4tx     unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x49  0xFF92   1   no   ivVcan4rx     unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x4A  0xFF94   1   no   ivVcan4err    unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x4B  0xFF96   1   no   ivVcan4wkup   unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x4C  0xFF98   1   no   ivVcan3tx     unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x4D  0xFF9A   1   no   ivVcan3rx     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x4E  0xFF9C   1   no   ivVcan3err    unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x4F  0xFF9E   1   no   ivVcan3wkup   unused by PE */
  INT_CFADDR = 160U;                                      
  INT_CFDATA0 = 1U;                    /*  0x50  0xFFA0   1   no   ivVcan2tx     used by PE */
  INT_CFDATA1 = 1U;                    /*  0x51  0xFFA2   1   no   ivVcan2rx     used by PE */
  INT_CFDATA2 = 1U;                    /*  0x52  0xFFA4   1   no   ivVcan2err    used by PE */
  INT_CFDATA3 = 1U;                    /*  0x53  0xFFA6   1   no   ivVcan2wkup   used by PE */
  INT_CFDATA4 = 1U;                    /*  0x54  0xFFA8   1   no   ivVcan1tx     used by PE */
  INT_CFDATA5 = 1U;                    /*  0x55  0xFFAA   1   no   ivVcan1rx     used by PE */
  INT_CFDATA6 = 1U;                    /*  0x56  0xFFAC   1   no   ivVcan1err    used by PE */
  INT_CFDATA7 = 1U;                    /*  0x57  0xFFAE   1   no   ivVcan1wkup   used by PE */
  INT_CFADDR = 176U;                                      
  INT_CFDATA0 = 1U;                    /*  0x58  0xFFB0   1   no   ivVcan0tx     used by PE */
  INT_CFDATA1 = 1U;                    /*  0x59  0xFFB2   1   no   ivVcan0rx     used by PE */
  INT_CFDATA2 = 1U;                    /*  0x5A  0xFFB4   1   no   ivVcan0err    used by PE */
  INT_CFDATA3 = 1U;                    /*  0x5B  0xFFB6   1   no   ivVcan0wkup   used by PE */
  INT_CFDATA4 = 1U;                    /*  0x5C  0xFFB8   1   no   ivVflash      unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x5D  0xFFBA   1   no   ivVeeprom     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x5E  0xFFBC   1   no   ivVspi2       unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x5F  0xFFBE   1   no   ivVspi1       unused by PE */
  INT_CFADDR = 192U;                                      
  INT_CFDATA0 = 1U;                    /*  0x60  0xFFC0   1   no   ivViic0       used by PE */
  INT_CFDATA1 = 1U;                    /*  0x61  0xFFC2   1   no   ivVReserved30 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x62  0xFFC4   1   no   ivVcrgscm     unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x63  0xFFC6   1   no   ivVcrgplllck  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x64  0xFFC8   1   no   ivVtimpabovf  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x65  0xFFCA   1   no   ivVtimmdcu    unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x66  0xFFCC   1   no   ivVporth      used by PE */
  INT_CFDATA7 = 1U;                    /*  0x67  0xFFCE   1   no   ivVportj      unused by PE */
  INT_CFADDR = 208U;                                      
  INT_CFDATA0 = 1U;                    /*  0x68  0xFFD0   1   no   ivVatd1       unused by PE */
  INT_CFDATA1 = 3U;                    /*  0x69  0xFFD2   3   no   ivVatd0       used by PE */
  INT_CFDATA2 = 1U;                    /*  0x6A  0xFFD4   1   no   ivVsci1       unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x6B  0xFFD6   1   no   ivVsci0       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x6C  0xFFD8   1   no   ivVspi0       used by PE */
  INT_CFDATA5 = 1U;                    /*  0x6D  0xFFDA   1   no   ivVtimpaie    unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x6E  0xFFDC   1   no   ivVtimpaaovf  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x6F  0xFFDE   1   no   ivVtimovf     unused by PE */
  INT_CFADDR = 224U;                                      
  INT_CFDATA0 = 1U;                    /*  0x70  0xFFE0   1   no   ivVtimch7     unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x71  0xFFE2   1   no   ivVtimch6     unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x72  0xFFE4   1   no   ivVtimch5     unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x73  0xFFE6   1   no   ivVtimch4     unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x74  0xFFE8   1   no   ivVtimch3     unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x75  0xFFEA   1   no   ivVtimch2     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x76  0xFFEC   1   no   ivVtimch1     unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x77  0xFFEE   1   no   ivVtimch0     unused by PE */
  INT_CFADDR = 240U;                                      
  INT_CFDATA0 = 4U;                    /*  0x78  0xFFF0   4   no   ivVrti        used by PE */
  INT_CFDATA1 = 1U;                    /*  0x79  0xFFF2   1   no   ivVirq        unused by PE */
  /* Common initialization of the CPU registers */
  /* RDRM: RDRM7=1,RDRM6=1,RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  RDRM = 192U;                                      
  /* PERS: PERS6=0 */
  PERS &= (unsigned char)~(unsigned char)64U;                     
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=1,RDRS3=1,RDRS2=1,RDRS1=1,RDRS0=1 */
  RDRS = 31U;                                      
  /* PPSS: PPSS4=1 */
  PPSS |= (unsigned char)16U;                      
  /* PERJ: PERJ7=0,PERJ6=0 */
  PERJ &= (unsigned char)~(unsigned char)192U;                     
  /* RDRJ: RDRJ1=1,RDRJ0=1 */
  RDRJ |= (unsigned char)3U;                      
  /* COPCTL: WCOP=0,RSBCK=1,CR2=0,CR1=0,CR0=0 */
  COPCTL = (COPCTL & (unsigned char)~(unsigned char)135U) | (unsigned char)64U;
  /* RDRIV: RDPB=1 */
  RDRIV |= (unsigned char)2U;                      
  /* RDR1AD1: RDR1AD115=1,RDR1AD114=1,RDR1AD113=1,RDR1AD112=1,RDR1AD111=1,RDR1AD110=1,RDR1AD19=1,RDR1AD18=1 */
  RDR1AD1 = 255U;                                      
  /* RDRH: RDRH7=1,RDRH6=1,RDRH5=1,RDRH4=1,RDRH3=1,RDRH2=1,RDRH1=0,RDRH0=1 */
  RDRH = 253U;                                      
  /* RDRP: RDRP7=1,RDRP6=1,RDRP5=1,RDRP4=1,RDRP3=1,RDRP2=1,RDRP1=1,RDRP0=1 */
  RDRP = 255U;                                      
  /* RDRT: RDRT7=1,RDRT6=1,RDRT5=1,RDRT4=1,RDRT3=1,RDRT2=1,RDRT1=1,RDRT0=1 */
  RDRT = 255U;                                      
  /* RDR1AD0: RDR1AD07=1,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  RDR1AD0 = 128U;                                      
  /* IRQCR: IRQEN=0 */
  IRQCR &= (unsigned char)~(unsigned char)64U;                     
  /* ### Init_GPIO init code */
  /* PORTA: PA7=1,PA6=1,PA5=1,PA4=1,PA3=1,PA2=1,PA1=1,PA0=1 */
  PORTA = 255U;                                      
  /* DDRA: DDRA7=1,DDRA6=1,DDRA5=1,DDRA4=1,DDRA3=1,DDRA2=1,DDRA1=1,DDRA0=1 */
  DDRA = 255U;                                      
  /* ### Init_GPIO init code */
  /* PPSH: PPSH0=1 */
  PPSH |= (unsigned char)1U;                      
  /* PERH: PERH0=1 */
  PERH |= (unsigned char)1U;                      
  /* DDRH: DDRH0=1 */
  DDRH |= (unsigned char)1U;                      
  /* PIEH: PIEH7=1,PIEH6=1,PIEH5=1,PIEH4=1,PIEH3=0,PIEH2=0,PIEH1=0,PIEH0=0 */
  PIEH = 240U;                                      
  /* ### Init_MSCAN init code */
  /* CAN1CTL1: CANE=1,CLKSRC=0,LOOPB=0,LISTEN=1,BORM=0,WUPM=0,SLPAK=0,INITAK=1 */
  CAN1CTL1 = 145U;                                      
  /* ### Init_MSCAN init code */
  /* CAN2CTL1: CANE=1,CLKSRC=0,LOOPB=0,LISTEN=1,BORM=0,WUPM=0,SLPAK=0,INITAK=1 */
  CAN2CTL1 = 145U;                                      
  /* ### Init_SPI init code */
  /* SPI0BR: SPPR2=1,SPPR1=0,SPPR0=0,SPR2=0,SPR1=1,SPR0=0 */
  SPI0BR = 66U;                                      
  /* SPI0CR1: SPIE=0,SPE=1,SPTIE=0,MSTR=1,CPOL=0,CPHA=0,SSOE=0,LSBFE=0 */
  SPI0CR1 = 80U;                                      
  /* ### Init_GPIO init code */
  /* PTS: PTS7=1 */
  PTS |= (unsigned char)128U;                      
  /* DDRS: DDRS7=1 */
  DDRS |= (unsigned char)128U;                      
  /* ### Init_IIC init code */
  /* IIC0_IBCR: IBEN=1 */
  IIC0_IBCR |= (unsigned char)128U;    /* Enable the module */
  /* IIC0_IBCR: IBEN=1,IBIE=1,MS_SL=0,TX_RX=0,TXAK=0,RSTA=0,IBSWAI=0 */
  IIC0_IBCR = 192U;                    /* Control register setting */
  /* ### Init_MSCAN init code */
  /* CAN0CTL1: CANE=1,CLKSRC=0,LOOPB=0,LISTEN=1,BORM=0,WUPM=0,SLPAK=0,INITAK=1 */
  CAN0CTL1 = 145U;                                      
  /* ### Init_GPIO init code */
  /* PORTK: PK2=0,PK1=0 */
  PORTK &= (unsigned char)~(unsigned char)6U;                     
  /* PUCR: PUPKE=0 */
  PUCR &= (unsigned char)~(unsigned char)128U;                     
  /* DDRK: DDRK2=1,DDRK1=1 */
  DDRK |= (unsigned char)6U;                      
  /* ### Init_GPIO init code */
  /* PUCR: PUPEE=0 */
  PUCR &= (unsigned char)~(unsigned char)16U;                     
  /* ### Init_ADC init code */
  /* Initialization of the ADC0 module */
  /* ATD0CTL3: S8C=0,S4C=1,S2C=1,S1C=1,FIFO=0,FRZ1=1,FRZ0=0 */
  ATD0CTL3 = 58U;                                      
  /* ATD0CTL4: SRES8=0,SMP1=1,SMP0=1,PRS4=1,PRS3=0,PRS2=0,PRS1=1,PRS0=1 */
  ATD0CTL4 = 115U;                                      
  /* ATD0CTL2: ADPU=1,AFFC=0,AWAI=0,ETRIGLE=0,ETRIGP=0,ETRIGE=0,ASCIE=1,ASCIF=0 */
  ATD0CTL2 = 130U;                                      
  /*
     The following delay loop generates a delay of approx. 20us, which is needed for
     the module to recover from power down state.
  */
  asm {
    /*
     * Delay
     *   - requested                  : 20 us @ 40MHz,
     *   - possible                   : 800 c, 20000 ns
     */
    pshd                               /* (2 c: 50 ns) backup D */
    ldd #72                            /* (2 c: 50 ns) number of iterations */
    label0:
    movb #85,ARMCOP                    /* Reset watchdog counter - 2x write*/
    movb #170,ARMCOP
    dbne d, label0                     /* (3 c: 75 ns) repeat 72x */
    puld                               /* (3 c: 75 ns) restore D */
    nop                                /* (1 c: 25 ns) wait for 1 c */
  };
  /* ATD0CTL5: DJM=1,DSGN=0,SCAN=1,MULT=1,CC=0,CB=0,CA=0 */
  ATD0CTL5 = 176U;                                      
  /* ### Init_RTI init code */
  /* PLLCTL: PRE=1 */
  PLLCTL |= (unsigned char)4U;                      
  /* CRGINT: RTIE=1 */
  CRGINT |= (unsigned char)128U;                      
  /* RTICTL: RTDEC=1,RTR6=0,RTR5=0,RTR4=0,RTR3=0,RTR2=0,RTR1=1,RTR0=1 */
  RTICTL = 131U;                                      
  /* ### Init_COP init code */
  /* PLLCTL: PCE=1 */
  PLLCTL |= (unsigned char)2U;                      
  /* ### */
  /* Initial interrupt priority */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm CLI;                             /* Enable interrupts */
  /*lint -restore Enable MISRA rule (1.1) checking. */
} /*MCU_init*/

#pragma MESSAGE DEFAULT C12056

/*lint -save  -e765 Disable MISRA rule (8.10) checking. */
#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isr_default
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isr_default(void)
{
    PORTA = 0xFF;
}
/* end of isr_default */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan2tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan2tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan2tx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan2rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan2rx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan2rx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan2err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan2err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan2err */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan2wkup
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan2wkup(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan2wkup */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan1tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan1tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan1tx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan1rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan1rx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan1rx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan1err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan1err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan1err */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan1wkup
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan1wkup(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan1wkup */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0tx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0rx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0rx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0err */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0wkup
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0wkup(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0wkup */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrViic0
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrViic0(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrViic0 */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : IsrPortH
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void IsrPortH(void)
{
  //INS interrupt
  
  PORTA_PA6 = ~PORTA_PA6;
  PIFH = 1;
}
/* end of IsrPortH */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : IsrAtd0
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void IsrAtd0(void)
{
    unsigned int curFreins, curAccel1, curAccel2;
    
    ATD1STAT0_SCF = 1;
    
    //On tient une moyenne mobile exponentielle sur les valeurs mesurées.
    //xt_moy = alpha*xt + (1-alpha)*xt-1_moy,  alpha = 2/(N+1)
    //Le coefficient de lissage alpha est égal à 0.125 ce qui veut dire
    //que les 15 dernières mesures portent 86% du poids de la moyenne.
    //À environ une mesure par 200 us, c'est une moyenne sur 3 ms.
    
    curFreins = ATD0DR5; //H & ATD0DR0L;
    freins = curFreins + (8-1)*freins;
    freins >>= 3; 
   
    curAccel1 = ATD0DR3; //ATD0DR1; //H & ATD0DR1L;
    accel1 = curAccel1 + (8-1)*accel1;
    accel1 >>= 3; 
    
    curAccel2 = ATD0DR1; //ATD0DR3; //H & ATD0DR2L;
    accel2 = curAccel2 + (8-1)*accel2;
    accel2 >>= 3; 

    //Get accel
    SafetyCheck();
}
/* end of IsrAtd0 */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVspi0
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVspi0(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVspi0 */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : IsrRti
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void IsrRti(void)
{
    //Envoyer accel au DAC
    SpiSend(accel);
    
    //Émettre le son 'ready to drive' pour 2 secondes après réception du signal des drives
    emitReadyToDriveSound();

    _FEED_COP();
    CRGFLG_RTIF = 1;
}
/* end of IsrRti */
#pragma CODE_SEG DEFAULT


/*lint -restore Enable MISRA rule (8.10) checking. */

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */




/* Interrupt vector table */

extern void near IsrCop(void);

/* ISR prototype */
typedef void (*near tIsrFunc)(void);

#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR isr_default   /* unassigned interrupt service routine */
#endif
/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static const tIsrFunc _InterruptVectorTable[] @0xFF10U = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* ISR name                               No.  Address Pri XGATE Name          Description */
  &UNASSIGNED_ISR,                      /* 0x08  0xFF10   -   -    ivVsi         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x09  0xFF12   1   no   ivReserved119 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0A  0xFF14   1   no   ivReserved118 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0B  0xFF16   1   no   ivReserved117 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0C  0xFF18   1   no   ivReserved116 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0D  0xFF1A   1   no   ivReserved115 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0E  0xFF1C   1   no   ivReserved114 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0F  0xFF1E   1   no   ivReserved113 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x10  0xFF20   1   no   ivReserved112 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x11  0xFF22   1   no   ivReserved111 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x12  0xFF24   1   no   ivReserved110 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x13  0xFF26   1   no   ivReserved109 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x14  0xFF28   1   no   ivReserved108 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x15  0xFF2A   1   no   ivReserved107 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x16  0xFF2C   1   no   ivReserved106 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x17  0xFF2E   1   no   ivReserved105 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x18  0xFF30   1   no   ivReserved104 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x19  0xFF32   1   no   ivReserved103 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1A  0xFF34   1   no   ivReserved102 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1B  0xFF36   1   no   ivReserved101 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1C  0xFF38   1   no   ivReserved100 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1D  0xFF3A   1   no   ivReserved99  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1E  0xFF3C   1   no   ivReserved98  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1F  0xFF3E   1   no   ivReserved97  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x20  0xFF40   1   no   ivReserved96  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x21  0xFF42   1   no   ivReserved95  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x22  0xFF44   1   no   ivReserved94  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x23  0xFF46   1   no   ivReserved93  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x24  0xFF48   1   no   ivReserved92  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x25  0xFF4A   1   no   ivReserved91  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x26  0xFF4C   1   no   ivReserved90  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x27  0xFF4E   1   no   ivReserved89  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x28  0xFF50   1   no   ivReserved88  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x29  0xFF52   1   no   ivReserved87  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2A  0xFF54   1   no   ivReserved86  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2B  0xFF56   1   no   ivReserved85  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2C  0xFF58   1   no   ivReserved84  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2D  0xFF5A   1   no   ivReserved83  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2E  0xFF5C   1   no   ivReserved82  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2F  0xFF5E   1   no   ivReserved81  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x30  0xFF60   1   -    ivVxsramav    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x31  0xFF62   1   -    ivVxsei       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x32  0xFF64   1   no   ivVxst7       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x33  0xFF66   1   no   ivVxst6       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x34  0xFF68   1   no   ivVxst5       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x35  0xFF6A   1   no   ivVxst4       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x36  0xFF6C   1   no   ivVxst3       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x37  0xFF6E   1   no   ivVxst2       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x38  0xFF70   1   no   ivVxst1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x39  0xFF72   1   no   ivVxst0       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3A  0xFF74   1   no   ivVpit3       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3B  0xFF76   1   no   ivVpit2       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3C  0xFF78   1   no   ivVpit1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3D  0xFF7A   1   no   ivVpit0       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3E  0xFF7C   1   no   ivVReserved65 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3F  0xFF7E   1   no   ivVapi        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x40  0xFF80   1   no   ivVlvi        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x41  0xFF82   1   no   ivVReserved62 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x42  0xFF84   1   no   ivVsci5       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x43  0xFF86   1   no   ivVsci4       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x44  0xFF88   1   no   ivVsci3       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x45  0xFF8A   1   no   ivVsci2       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x46  0xFF8C   1   no   ivVpwmesdn    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x47  0xFF8E   1   no   ivVportp      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x48  0xFF90   1   no   ivVcan4tx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x49  0xFF92   1   no   ivVcan4rx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4A  0xFF94   1   no   ivVcan4err    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4B  0xFF96   1   no   ivVcan4wkup   unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4C  0xFF98   1   no   ivVcan3tx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4D  0xFF9A   1   no   ivVcan3rx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4E  0xFF9C   1   no   ivVcan3err    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4F  0xFF9E   1   no   ivVcan3wkup   unused by PE */
  &isrVcan2tx,                          /* 0x50  0xFFA0   1   no   ivVcan2tx     used by PE */
  &isrVcan2rx,                          /* 0x51  0xFFA2   1   no   ivVcan2rx     used by PE */
  &isrVcan2err,                         /* 0x52  0xFFA4   1   no   ivVcan2err    used by PE */
  &isrVcan2wkup,                        /* 0x53  0xFFA6   1   no   ivVcan2wkup   used by PE */
  &isrVcan1tx,                          /* 0x54  0xFFA8   1   no   ivVcan1tx     used by PE */
  &isrVcan1rx,                          /* 0x55  0xFFAA   1   no   ivVcan1rx     used by PE */
  &isrVcan1err,                         /* 0x56  0xFFAC   1   no   ivVcan1err    used by PE */
  &isrVcan1wkup,                        /* 0x57  0xFFAE   1   no   ivVcan1wkup   used by PE */
  &isrVcan0tx,                          /* 0x58  0xFFB0   1   no   ivVcan0tx     used by PE */
  &isrVcan0rx,                          /* 0x59  0xFFB2   1   no   ivVcan0rx     used by PE */
  &isrVcan0err,                         /* 0x5A  0xFFB4   1   no   ivVcan0err    used by PE */
  &isrVcan0wkup,                        /* 0x5B  0xFFB6   1   no   ivVcan0wkup   used by PE */
  &UNASSIGNED_ISR,                      /* 0x5C  0xFFB8   1   no   ivVflash      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5D  0xFFBA   1   no   ivVeeprom     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5E  0xFFBC   1   no   ivVspi2       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5F  0xFFBE   1   no   ivVspi1       unused by PE */
  &isrViic0,                            /* 0x60  0xFFC0   1   no   ivViic0       used by PE */
  &UNASSIGNED_ISR,                      /* 0x61  0xFFC2   1   no   ivVReserved30 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x62  0xFFC4   1   no   ivVcrgscm     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x63  0xFFC6   1   no   ivVcrgplllck  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x64  0xFFC8   1   no   ivVtimpabovf  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x65  0xFFCA   1   no   ivVtimmdcu    unused by PE */
  &IsrPortH,                            /* 0x66  0xFFCC   1   no   ivVporth      used by PE */
  &UNASSIGNED_ISR,                      /* 0x67  0xFFCE   1   no   ivVportj      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x68  0xFFD0   1   no   ivVatd1       unused by PE */
  &IsrAtd0,                             /* 0x69  0xFFD2   3   no   ivVatd0       used by PE */
  &UNASSIGNED_ISR,                      /* 0x6A  0xFFD4   1   no   ivVsci1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6B  0xFFD6   1   no   ivVsci0       unused by PE */
  &isrVspi0,                            /* 0x6C  0xFFD8   1   no   ivVspi0       used by PE */
  &UNASSIGNED_ISR,                      /* 0x6D  0xFFDA   1   no   ivVtimpaie    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6E  0xFFDC   1   no   ivVtimpaaovf  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6F  0xFFDE   1   no   ivVtimovf     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x70  0xFFE0   1   no   ivVtimch7     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x71  0xFFE2   1   no   ivVtimch6     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x72  0xFFE4   1   no   ivVtimch5     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x73  0xFFE6   1   no   ivVtimch4     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x74  0xFFE8   1   no   ivVtimch3     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x75  0xFFEA   1   no   ivVtimch2     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x76  0xFFEC   1   no   ivVtimch1     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x77  0xFFEE   1   no   ivVtimch0     unused by PE */
  &IsrRti,                              /* 0x78  0xFFF0   4   no   ivVrti        used by PE */
  &UNASSIGNED_ISR,                      /* 0x79  0xFFF2   1   no   ivVirq        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x7A  0xFFF4   -   -    ivVxirq       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x7B  0xFFF6   -   -    ivVswi        unused by PE */
  &UNASSIGNED_ISR                       /* 0x7C  0xFFF8   -   -    ivVtrap       unused by PE */
};

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static const tIsrFunc _ResetVectorTable[] @0xFFFAU = { /* Reset vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* Reset handler name                    Address Name           Description */
  &IsrCop,                              /* 0xFFFA  ivVcop         used by PE */
  &MCU_init_reset,                      /* 0xFFFC  ivVclkmon      unused by PE */
  &MCU_init_reset                       /* 0xFFFE  ivVreset       used by PE */
};



#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVportp
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVportp(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVportp */


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVportj
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVportj(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVportj */

/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
